### PR TITLE
Removed duplicate declaration of the Forecast class Feature/#71

### LINKED ISSUE #71: Duplicación de clase Forecast
La clase Forecast está duplicada en el archivo forecast.js, generando redundancia y complicaciones en la lectura del código. Se requiere la eliminación de la declaración duplicada para mantener la claridad y concisión en el proyecto.

### PR DESCRIPTION
**Pull request by dinho-dev**
This pull request addresses the issue of duplicate declaration of the Forecast class in forecast.js. The duplicate declaration has been removed, ensuring code clarity and eliminating redundancy. This change simplifies the codebase and improves maintainability.
closes #71

### CODE REVIEW

**Comment by dinho-dev** [comment]
Revisar @JJ

**Comment by JJ** [comment]
Estas cosas tan simples no hace falta que yo las revise...

**Review by DaniWalkington — APPROVED** [review]
LGTM 👍

**Comment by dinho-dev** [comment]
> Estas cosas tan simples no hace falta que yo las revise...

okay 🫡

**Comment by VickyTinar** [comment]
LGTM

**Review by VickyTinar — APPROVED** [review]

**Pull request merged**
